name: "Performance request"
description: "기능 고도화 또는 성능/구조 최적화를 위한 이슈 템플릿입니다. 생성된 이슈는 Jira와 연동됩니다."
labels: [performance]
title: "[PERF] 이슈 이름을 작성해주세요"
body:
  - type: dropdown
    id: issuetype
    attributes:
      label: "🔖 이슈 유형 (Jira Issue Type)"
      description: "Jira 상에서 사용할 이슈 타입을 선택해주세요"
      options:
        - Task
        - Sub-task
        - Story
        - Epic
    validations:
      required: true

  - type: input
    id: parentKey
    attributes:
      label: "🎟️ 상위 작업 (Ticket Number)"
      description: "연결할 상위 Jira 티켓 키(BADA-00) 를 입력해주세요"
      placeholder: "BADA-00"
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: "🌳 브랜치명 (Branch)"
      description: "영어로 브랜치명을 작성해주세요"
      placeholder: "performance/BADA-00-New_Performance"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "🧪 개선 내용"
      description: "어떤 기능을 어떻게 개선하려는지 적어주세요."
      placeholder: "예: 쿼리 최적화로 검색 속도를 개선합니다."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "✅ To-do"
      description: "최적화 및 개선을 위한 세부 작업 목록을 작성해주세요."
      value: |
        - [ ] todo 1
        - [ ] todo 2
        - [ ] todo 3
        - [ ] todo 4
    validations:
      required: true
